### PR TITLE
enhancement: removed dependence on hard-coded api key. updated docume…

### PR DESCRIPTION
**Pull request by kreig303**
…ntation for clarity. added expo-cli as dev dependency. removed commented out code.

Per #3:

1. edited `.gitignore` for `.env`files
1. removed dependence on hard-coded api key in `./src/api/api.js`
1. stripped hard-coded api key out of `.src/api.mockResponses.js`
1.  added in `metro-react-native-babel-preset` and `babel-plugin-dotenv-import` as `devDependencies` and modified `./babel.config.js` to load them at build
1. added in `.env.sample` file
1. modified `.travis.yml` both to clean it up and utilize the changes properly
1. `README.md` updated

Per #5:

1. `codecov` and `expo-cli` added to `devDependencies`

Additional changes:

1. removed one line of commented out code

### CODE REVIEW

**Comment by kreig303** [comment]
Ah! I see now I failed to account for the new `API_KEY` variable in the Jest tests in `./__tests__`/api/api.test.js`.

Will fix that. DO NOT MERGE until I am done. :)

**Comment by kreig303** [comment]
The problem ran more deeply than "fixing the tests".

There are two issues with `react-native-dotenv`'s implementation:
1. ignores environment variables which are set in the normal fashion
2. `.env` variables are seemingly cached for some period of time

I will attempt to fix this by forking the relevant project.

In the meanwhile, the workaround was to include a `.env.sample` file (which in any case is good form) and then rename it when the travis-ci build is invoked. This is mildly fragile as some forks might just rename the file to reuse, but that's their problem. :-D

**Comment by kreig303** [comment]
Did a proper fix... swapped out the stale `react-native-dotenv` for a more robust and updated `babel-plugin-dotenv-import`.

Now this works as intended! and shell environment vars take precedence over `.env` vars, as god intended.

**Comment by kreig303** [comment]
No idea why the project-level `codecov` test is marked as failed but shouldn't actually impact functionality.

**Comment by PedroBern** [comment]
> No idea why the project-level codecov test is marked as failed but shouldn't actually impact functionality.

Sometimes this happens, not a problem.

Thanks for the PR! I will look more into it later, great job!

**Comment by kreig303** [comment]
> Thanks for the PR! I will look more into it later, great job!

Please... I don't need an attaboy.

**Comment by kreig303** [comment]
Further cleanup in `./.travis.yml`...
1. No need to specify `yarn test` as a job. Travis runs this by default... which of course seems obvious now. :/
1. Cleanup of "Coverage" stage. Maybe this will reduce the chance of that strange error.

**Pull request merged**
